[workspace]

members = [
    "commons",
    "demo",
    "engine",
    "terrain_gen"
]

[workspace.dependencies]
image = "0.24.1"
glium = "0.31.0"
maplit = "1.0"
nalgebra = "0.31.0"
num = "0.4"
simdnoise = "3.1.6"
tempfile = "3"
thiserror = "1.0.37"