[workspace]

members = [
    "commons",
    "demo",
    "engine",
    "network",
    "terrain_gen"
]

[workspace.dependencies]
image = "0"
glium = "0"
maplit = "1"
nalgebra = "0"
num = "0"
simdnoise = "3"
tempfile = "3"
thiserror = "1"